### ISSUE TITLE
Are you want to solve this problem?

### ISSUE THREAD

**Issue by 459696649** [L7NEG/Ultimate-Menu#20]
Hello friends, can I ask a small question? Why can't the function of spawn vehicles be used in missions? ? When there is a personal vehicle in the free session, the vehicle cannot be spawned. Is there any code that can solve this? ?

**Comment by L7NEG** [comment]
> Hello friends, can I ask a small question? Why can't the function of spawn vehicles be used in missions? ? When there is a personal vehicle in the free session, the vehicle cannot be spawned. Is there any code that can solve this? ?

just make sure your personal vehicle is not outside of your garage + it is not possible to be fixed soon you can use yimmenu
