### ISSUE TITLE
Remove My Scripts

### ISSUE THREAD

**Issue by ShinyWasabi** [L7NEG/Ultimate-Menu#23]
Who the hell gave you the permission to paste my scripts into your crap? You can't just get away by giving credit. Remove them all from both this repo and the one in YimMenu-Lua.

**Comment by L7NEG** [comment]
As you just Closed this https://github.com/YimMenu-Lua/GunVan/pull/1 without merging it that's why I will keep it + I'm trying to be respectful to your work instead that's how you treat me then np

**Comment by L7NEG** [comment]
+ your repos are already open src = open for anyone to update or maintain it as long as giving proper credits to its author

**Comment by lhwe** [comment]
LMAOOO

**Comment by L7NEG** [comment]
Fr xD
