### ISSUE TITLE
NOT WORKING ON YIM 

### ISSUE THREAD

**Issue by 99-99itm** [L7NEG/Ultimate-Menu#9]
gives errors while running on yim

**Comment by L7NEG** [comment]
Because the V18 one is only for kiddions only bro I will update YimMenu V2 One Later

**Comment by Dytolins** [comment]
And where to find kiddons mod menu?

**Comment by 99-99itm** [comment]
> Because the V18 one is only for kiddions only bro I will update YimMenu V2 One Later

I SEE CANT WAIT FOR THR UPDATE

**Comment by L7NEG** [comment]
Soon bro 🔥

**Comment by 99-99itm** [comment]
> Soon bro 🔥
🥲🥲🥲
hii .. hmm may i ask an u make an script where u can remove bad sport and reports like in kiddons .. .. i really need that ... that would be really really helpful

**Comment by L7NEG** [comment]
It's already in Ultimate Menu kiddions script in Self section
